@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

abstract class Customer {
  - username: String
  - address: String
  - phone: PhoneNumber
  - email: EmailAddress
  - password: String
  - profilePicture: File

--
    + Customer(username: String, address: String, phone: PhoneNumber, email: EmailAddress, password: String)
.. Getters ..
    + getAddress(): String
    + getPhone(): PhoneNumber
    + getEmail(): EmailAddress
    + getUsername(): String
    + getPassword(): String
    + getProfilePicture(): File
.. Setters ..
    + setAddress(address: String): void
    + setPhone(phone: PhoneNumber): void
    + setEmail(email: EmailAddress): void
    + setUsername(username: String): void
    + setPassword(password: String): void
    + setProfilePicture(profilePicture: File): void
 }
' PhoneNumber class
 class PhoneNumber {
    - regionCode: String
    - localNumber: String

    + PhoneNumber(regionCode: String, localNumber: String)
    + getRegionCode(): String
    + getLocalNumber(): String
    + setRegionCode(regionCode: String): void
    + setLocalNumber(localNumber: String): void
    + isValid(): boolean
}
PhoneNumber --* Customer

class EmailAddress {
    - email: String

    + EmailAddress(email: String)
    + getEmail(): String
    + setEmail(email: String): void
    + isValid(): boolean
}
EmailAddress --* Customer

class User extends Customer {
    - title: String
    - firstName: String
    - lastName: String
    - dateOfBirth: Date
    - isLockingForNewJobs: boolean
    - cv: File
    - jobApplications: JobApplication[]
    - skills: Skill[]
    - education: Education[]
    - certificates: Certificate[]
    - languages: Language[]
    - interests: Interest[]
    - references: Reference[]

--
    + User(username: String, address: String, phone: PhoneNumber, email: EmailAddress, password: String, firstName: String, lastName: String, dateOfBirth: Date, cv: File, profilePicture: File)
.. Getters ..
    + getTitle(): String
    + getFirstName(): String
    + getLastName(): String
    + getDateOfBirth(): Date
    + getCv(): File
    + getJobApplications(): JobApplication[]
    + getSkills(): Skill[]
    + getEducation(): Education[]
    + getCertificates(): Certificate[]
    + getLanguages(): Language[]
    + getInterests(): Interest[]
    + getReferences(): Reference[]
.. Setters ..
    + setTitle(title: String): void
    + setFirstName(firstName: String): void
    + setLastName(lastName: String): void
    + setDateOfBirth(dateOfBirth: Date): void
    + setCv(cv: File): void
    ' Add methods to add and remove
-- Add methods to add and remove --
    + addJobApplication(jobApplication: JobApplication): void
    + addSkill(skill: Skill): void
    + addEducation(education: Education): void
    + addCertificate(certificate: Certificate): void
    + addLanguage(language: Language): void
    + addInterest(interest: Interest): void
..
    + addReference(reference: Reference): void
    + removeJobOffer(jobOffer: JobOffer): void
    + removeJobApplication(jobApplication: JobApplication): void
    + removeSkill(skill: Skill): void
    + removeEducation(education: Education): void
    + removeCertificate(certificate: Certificate): void
    + removeLanguage(language: Language): void
    + removeInterest(interest: Interest): void
    + removeReference(reference: Reference): void
}

class Company extends Customer {
    - name: String
    - description: String
    - website: HyperLink
    - fellows: User[]
    - fields: Field[]
    - jobOffers: JobOffer[]
    - members: User[]
    - ratings: Rating[]
--
    + Company(name: String, username: String, address: String, phone: PhoneNumber, email: EmailAddress, password: String, name: String, description: String, website: HyperLink, profilePicture: File)
.. Getters ..
    + getName(): String
    + getDescription(): String
    + getWebsite(): HyperLink
    + getFellows(): User[]
    + getFields(): Field[]
    + getJobOffers(): JobOffer[]
    + getMembers(): User[]
    + getRatings(): Rating[]
.. Setters ..
    + setName(name: String): void
    + setDescription(description: String): void
    + setWebsite(website: HyperLink): void
-- Add methods to add and remove --
    + addFellow(fellow: User): void
    + addField(field: Field): void
    + addJobOffer(jobOffer: JobOffer): void
    + addMember(member: User): void
    + addRating(rating: Rating): void
..
    + removeFellow(fellow: User): void
    + removeField(field: Field): void
    + removeJobOffer(jobOffer: JobOffer): void
    + removeMember(member: User): void
    + removeRating(rating: Rating): void
}

class profilefields.Skill {
    - name: String
    - level: String
    - description: String
--
    + Skill(name: String, level: String, description: String)
..
    + getName(): String
    + getLevel(): String
    + getDescription(): String
..
    + setName(name: String): void
    + setLevel(level: String): void
    + setDescription(description: String): void
}
profilefields.Skill -* User

class profilefields.Education {
    - name: String
    - level: String
    - gpa: double
    - description: String
    - startDate: Date
    - endDate: Date
--
    + Education(name: String, level: String, description: String, startDate: Date, endDate: Date)
..
    + getName(): String
    + getLevel(): String
    + getDescription(): String
..
    + setName(name: String): void
    + setLevel(level: String): void
    + setDescription(description: String): void
}
profilefields.Education --* User

class profilefields.Certificate {
    - name: String
    - description: String
    - giverCompany: Company
    - date: Date
    - attachment: Attachment
    - id: String
    - expirationDate: Date
--
    + Certificate(name: String, description: String, giverCompany: Company, date: Date, attachment: Attachment, id: String)
..
    + getName(): String
    + getDescription(): String
    + getGiverCompany(): Company
    + getDate(): Date
    + getAttachment(): Attachment
    + getId(): String
    + getExpirationDate(): Date
..
    + setName(name: String): void
    + setDescription(description: String): void
    + setGiverCompany(giverCompany: Company): void
    + setDate(date: Date): void
    + setAttachment(attachment: Attachment): void
    + setId(id: String): void
    + setExpirationDate(expirationDate: Date): void
..
    + isExpired(): boolean
}
profilefields.Certificate --* User
Company --* profilefields.Certificate

class Attachment {
    - attachmentLink: HyperLink
    - attachmentFile: File
--
    + Attachment(attachmentLink: HyperLink)
    + Attachment(attachmentFile: File)
..
    + getAttachmentLink(): HyperLink
    + getAttachmentFile(): File
}
Attachment --* profilefields.Certificate

class HyperLink {
    - link: String
--
    + HyperLink(link: String)
..
    + getLink(): String
    + setLink(link: String): void
..
    + isValid(): boolean
    + getTopLevelDomain(): String
    + getDomain(): String
    + getSubDomain(): String
}

HyperLink -* Attachment
HyperLink --* Company

abstract class AbstractProperty {
    - name: String
    - description: String
--
    + AbstractProperty(name: String, description: String)
..
    + getName(): String
    + getDescription(): String
..
    + setName(name: String): void
    + setDescription(description: String): void
}

class Field extends AbstractProperty {
    - tags: Tag[]

    + Field(name: String, description: String)
..
    + getTags(): Tag[]
..
    + addTag(tag: Tag): void
    + removeTag(tag: Tag): void
}

Field --* Company

class JobOffer extends AbstractProperty {
    - salary: double
    - location: String
    - startDate: Date
    - endDate: Date
    - company: Company
    - tags: Tag[]
    - jobApplications: JobApplication[]

--
    + JobOffer(title: String, description: String, salary: double, location: String, startDate: Date, endDate: Date, company: Company)
.. Getters ..
    + getSalary(): double
    + getLocation(): String
    + getStartDate(): Date
    + getEndDate(): Date
    + getCompany(): Company
    + getTags(): Tag[]
    + getJobApplications(): JobApplication[]
.. Setters ..
    + setSalary(salary: double): void
    + setLocation(location: String): void
    + setStartDate(startDate: Date): void
    + setEndDate(endDate: Date): void
    + setCompany(company: Company): void
}
JobOffer --* Company
Field --* JobOffer

class Tag extends AbstractProperty {

}
Field *-- Tag
JobOffer --* Tag

class Rating {
    - rating: float
    - comment: String
    - user: User
--
    + Rating(rating: float, comment: String, user: User)
..
    + getRating(): float
    + getComment(): String
    + getUser(): User
..
    + setRating(rating: float): void
    + setComment(comment: String): void
    + setUser(user: User): void
}
Rating --* Company

@enduml