@startuml
'https://plantuml.com/sequence-diagram

actor User as "User"

User -> Register : "User enter the register information"
Register --> User : "User enter not correct register information"

Register -> "Get more information"

"Get more information" --> Profile : "User enter the "Get more information or Press Skip button"

@enduml